# =============================================================================
# Netlify Configuration - Instituto Buriti (ÚNICA FONTE DA VERDADE)
# =============================================================================

[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  # Sincronizar com a versão usada na UI do Netlify ou definir a desejada
  NODE_VERSION = "22" 

# =============================================================================
# Redirecionamentos e Rewrites
# =============================================================================

# Forçar HTTPS
[[redirects]]
  from = "http://institutoburiti.com.br/*"
  to = "https://institutoburiti.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.institutoburiti.com.br/*"
  to = "https://www.institutoburiti.com.br/:splat"
  status = 301
  force = true

# Redirecionamentos legados
[[redirects]]
  from = "/home"
  to = "/desktop/index.html"
  status = 301

[[redirects]]
  from = "/sobre"
  to = "/desktop/index.html#sobre"
  status = 301

[[redirects]]
  from = "/cursos"
  to = "/desktop/index.html#cursos"
  status = 301

[[redirects]]
  from = "/contato"
  to = "/desktop/index.html#contato"
  status = 301

# Regra de fallback para 404 (deve vir por último)
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# Regra da raiz para servir o detector de dispositivo (deve vir antes do 404)
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# =============================================================================
# Cabeçalhos HTTP (Headers)
# =============================================================================

[[headers]]
  for = "/*"
  [headers.values]
    # Cabeçalhos de Segurança
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.html"
  [headers.values]
    # Cache curto para HTML para garantir que as atualizações sejam vistas rapidamente
    Cache-Control = "public, max-age=3600" # 1 hora

[[headers]]
  # Cache longo e imutável para assets estáticos
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

