# Netlify Configuration for Instituto Buriti
# This file configures smart device detection and routing

[build]
  # Build settings
  publish = "."
  command = "echo 'Static site - no build required'"

# Redirect rules for device detection
[[redirects]]
  # Root redirect to device detection
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Mobile version redirects
  from = "/mobile/*"
  to = "/mobile/:splat"
  status = 200

[[redirects]]
  # Desktop version redirects  
  from = "/desktop/*"
  to = "/desktop/:splat"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Performance headers
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.jpeg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.svg"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Error pages
[[redirects]]
  from = "/404"
  to = "/404.html"
  status = 404

# Force HTTPS
[[redirects]]
  from = "http://institutoburiti.com.br/*"
  to = "https://institutoburiti.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.institutoburiti.com.br/*"
  to = "https://www.institutoburiti.com.br/:splat"
  status = 301
  force = true

# Environment variables (if needed)
[build.environment]
  NODE_VERSION = "18"

