# =============================================================================
# Netlify Configuration - Instituto Buriti
# =============================================================================

[build]
  publish = "."
  command = "echo 'Static site - no build required'"

[build.environment]
  NODE_VERSION = "22" 

# =============================================================================
# Redirecionamentos e Rewrites
# =============================================================================
# Forçar HTTPS
[[redirects]]
  from = "http://institutoburiti.com.br/*"
  to = "https://institutoburiti.com.br/:splat"
  status = 301
  force = true
[[redirects]]
  from = "http://www.institutoburiti.com.br/*"
  to = "https://www.institutoburiti.com.br/:splat"
  status = 301
  force = true

# Regra da raiz para servir o detector de dispositivo
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Regra de fallback para 404
[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

# =============================================================================
# Cabeçalhos HTTP (Headers)
# =============================================================================
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# [[headers]]
#   # TEMPORARIAMENTE DESATIVADO PARA DEBUG - Cache longo e imutável para assets estáticos
#   for = "/*.js"
#   [headers.values]
#     Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.png"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
# ... (outras regras de imagem podem ser mantidas) ...